name: Test & Coverage

on: [push, pull_request]

jobs:
   tests:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup Bun
           uses: oven-sh/setup-bun@v2
           with:
              bun-version: latest

         - name: Install Dependencies
           run: bun install

         - name: Lint Code
           run: bun run lint

         - name: Build
           run: bun run build

         - name: Tests & Coverage
           run: bun run coverage

         - name: Report Coverage
           uses: codecov/codecov-action@v4
           with:
              token: ${{ secrets.CODECOV_TOKEN }}
              file: ./coverage/lcov.info
